### ISSUE TITLE
Generator results in error for ros2 monitor

### ISSUE THREAD

**Issue by iagosilvestre** [autonomy-and-verification-uol/ROSMonitoring#19]
Hey there,

I've been trying to set up ROSMonitoring using ROS Foxy and Ubuntu 20.04. I've been using the ros2 branch and whenever I try running ./generator --config_file offline_config.yaml the following error occurs:

  File "./generator", line 38
    destination_path: pathlib.Path
                    ^
SyntaxError: invalid syntax

I've tried analyzing the generator file but could not detect the issue in the line mentioned, do you have any idea what could be causing this ?

**Comment by AngeloFerrando** [comment]
Hi Iago,

Are you using Python3? Because from the error you are reporting seems you are using Python 2. Let me know if using Python 3 you are still getting the error.

Cheers,
Angelo

**Comment by iagosilvestre** [comment]
Hey There Angelo,

That was indeed the source of the issue, thanks for the help.

**Comment by iagosilvestre** [comment]
Sorry for the inconvenience Angelo but actually the error persisted. I mistakenly successfully compiled inside the generator folder and not the ros2_devel one.
![image](https://github.com/autonomy-and-verification-uol/ROSMonitoring/assets/32106546/f47cf86d-d5aa-468d-beda-138c0986f829)

**Comment by AngeloFerrando** [comment]
Hi Iago,

Weird, it is Indeed a problem with Python. In that line there Is a type hint which is not supporter in Python 2. I would suggest two things: 

1- Try to run the generator file through Python explicitly. That is, something like python3 ./generator --config_file and so on. Just to be sure that your are not running Python 2.

2- Remove that line from the file (line 38). It is not needed since it Is just an hint for the developers.

If neither of the two things I suggested work, let me know and I will think about other possible suggestions.

Cheers,
Angelo

**Comment by iagosilvestre** [comment]
Changing the first line from generator file from #!/usr/bin/env python to #!/usr/bin/env python3 for some reason changed the error to:
![image](https://github.com/autonomy-and-verification-uol/ROSMonitoring/assets/32106546/914fb8cd-062b-4414-879e-23f3103a4029)
I'm trying to detect the source of the problem but if you have any idea let me know.

**Comment by AngeloFerrando** [comment]
Try:

python3 -m pip install jedi

**Comment by iagosilvestre** [comment]
I believe that has solved the issue Angelo, I had to install prompt_toolkit as well but it seems to have compiled successfully and copied the files to my colcon workspace.

Thanks for the help!
